variables:
  SERVICE_NAME: "nextdealapp"

stages:
  - build
  - deploy

image: google/cloud-sdk:alpine
before_script:
    - gcloud config set project ${GCP_PROJECT_ID}
    - gcloud auth activate-service-account --key-file ${GOOGLE_CLOUD_CREDENTIALS}

build:
    stage: build
    only:
      - main
    script:
      - gcloud builds submit --tag gcr.io/${GCP_PROJECT_ID}/${SERVICE_NAME}


deploy-dev:
  environment: dev
  stage: deploy
  only:
    - main
  script:
    - gcloud run deploy ${SERVICE_NAME}-dev --image gcr.io/${GCP_PROJECT_ID}/${SERVICE_NAME} --region=us-central1 --platform managed --allow-unauthenticated --vpc-connector=${VPC_CONNECTOR} --min-instances=${MIN_INSTANCES} --max-instances=${MAX_INSTANCES} --timeout=50 --ingress=internal-and-cloud-load-balancing
