variables:
  SERVICE_NAME: "nextdealapp"

stages:
  - deploy-dev
  - deploy-staging

image: google/cloud-sdk:alpine

deploy-dev:
  environment: dev
  stage: deploy-dev
  only:
    - main
  before_script:
    - gcloud config set project ${GCP_PROJECT_ID}
    - gcloud auth activate-service-account --key-file ${GCP_SERVICE_ACCOUNT_DEPLOY}
  script:
    - gcloud builds submit --config cloudbuild.yaml .
    - gcloud run deploy ${SERVICE_NAME}-dev --image gcr.io/${GCP_PROJECT_ID}/${SERVICE_NAME} --service-account=${GCP_SERVICE_ACCOUNT_APP} --region=us-central1 --platform managed --allow-unauthenticated --set-env-vars="NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST},NEXT_PUBLIC_APP_HOST=${NEXT_PUBLIC_APP_HOST},NEXT_PUBLIC_LOCALE_LANG=${NEXT_PUBLIC_LOCALE_LANG},NEXT_PUBLIC_DEFAULT_LOCALE_LANG=${NEXT_PUBLIC_DEFAULT_LOCALE_LANG},NEXT_PUBLIC_DEFAULT_LOCALE_PREFIX=${NEXT_PUBLIC_DEFAULT_LOCALE_PREFIX},NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}" --vpc-connector=${VPC_CONNECTOR} --min-instances=${MIN_INSTANCES} --max-instances=${MAX_INSTANCES} --timeout=50 --ingress=internal-and-cloud-load-balancing

deploy-staging:
  environment: staging
  stage: deploy-staging
  only:
    - main
  before_script:
    - chmod +x ./setup_env.sh
    - bash ./setup_env.sh
    - gcloud config set project ${GCP_PROJECT_ID}
    - gcloud auth activate-service-account --key-file ${GCP_SERVICE_ACCOUNT_DEPLOY}
  script:
    - gcloud builds submit --tag gcr.io/${GCP_PROJECT_ID}/${SERVICE_NAME}
    - gcloud run deploy ${SERVICE_NAME}-staging --image gcr.io/${GCP_PROJECT_ID}/${SERVICE_NAME} --service-account=${GCP_SERVICE_ACCOUNT_APP} --region=us-central1 --platform managed --allow-unauthenticated --set-env-vars="NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST},NEXT_PUBLIC_APP_HOST=${NEXT_PUBLIC_APP_HOST},NEXT_PUBLIC_LOCALE_LANG=${NEXT_PUBLIC_LOCALE_LANG},NEXT_PUBLIC_DEFAULT_LOCALE_LANG=${NEXT_PUBLIC_DEFAULT_LOCALE_LANG},NEXT_PUBLIC_DEFAULT_LOCALE_PREFIX=${NEXT_PUBLIC_DEFAULT_LOCALE_PREFIX},NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}" --vpc-connector=${VPC_CONNECTOR} --min-instances=${MIN_INSTANCES} --max-instances=${MAX_INSTANCES} --timeout=50 --ingress=internal-and-cloud-load-balancing
  when: manual