FROM node:14

#Creates directories
RUN mkdir -p /usr/src/app

#Sets an environment variable
ENV PORT 8080
ENV NEXT_PUBLIC_API_HOST=https://service.nextdeal.dev/
ENV NEXT_PUBLIC_LOCALE_LANG=es
ENV NEXT_PUBLIC_DEFAULT_LOCALE_LANG=es
ENV NEXT_PUBLIC_DEFAULT_LOCALE_PREFIX=56
ENV NEXT_PUBLIC_APP_HOST=.nextdeal.dev
ENV NODE_ENV=development
ENV NEXT_PUBLIC_GRAFANA_HOST=https://metrics.nextdeal.dev
ENV NEXT_PUBLIC_WEB_HOST=wwww.nextdeal.dev

#Sets the working directory for any RUN, CMD, ENTRYPOINT, COPY, and ADD commands
WORKDIR /usr/src/app

#Copy new files or directories into the filesystem of the container
COPY package.json /usr/src/app
COPY package-lock.json /usr/src/app

#Execute commands in a new layer on top of the current image and commit the results
RUN npm install

##Copy new files or directories into the filesystem of the container
COPY . /usr/src/app

#Execute commands in a new layer on top of the current image and commit the results
RUN npm run build

#Informs container runtime that the container listens on the specified network ports at runtime
EXPOSE 8080

#Allows you to configure a container that will run as an executable
ENTRYPOINT ["npm", "start"]
