#!/bin/bash
echo NEXT_PUBLIC_API_HOST=$NEXT_PUBLIC_API_HOST >> .env.local
echo NEXT_PUBLIC_LOCALE_LANG=$NEXT_PUBLIC_LOCALE_LANG >> .env.local
echo NEXT_PUBLIC_DEFAULT_LOCALE_LANG=$NEXT_PUBLIC_DEFAULT_LOCALE_LANG >> .env.local
echo NEXT_PUBLIC_DEFAULT_LOCALE_PREFIX=$NEXT_PUBLIC_DEFAULT_LOCALE_PREFIX >> .env.local
echo NEXT_PUBLIC_APP_HOST=$NEXT_PUBLIC_APP_HOST >> .env.local
echo NODE_TLS_REJECT_UNAUTHORIZED=$NODE_TLS_REJECT_UNAUTHORIZED >> .env.local